<style type="text/css">
    header { display: none; }
    .login-container { margin: 20% auto; width: 500px; }
</style>

<div class="container">
    <form class="form-horizontal login-container" method="post">
        <div class="form-group">
            <label for="username" class="col-sm-2 control-label">username</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" id="username" placeholder="username" name="username" value="<?php echo isset($data['username']) ? $data['username'] : ''; ?>">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">password</label>
            <div class="col-sm-10">
                <input type="password" class="form-control" id="inputPassword3" placeholder="password" name="password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success form-control">Sign in</button>
            </div>
        </div>
    </form>
</div>